baseURL = 'https://example.org/'
languageCode = 'fr'
title = 'DJ RESCH'
theme = 'ananke'
enableEmoji = true
# enableRobotsTXT = true
# canonifyURLs = true
# paginate = 9
# enableInlineShortcodes = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Bienvenue sur le site officiel de DJ RESCH"
  author = "DJ RESCH"
  customCSS = ["css/custom.css"]
  favicon = "favicon/favicon-32x32.png"
  [params.Social_media.Facebook]
    Url = "https://example.com"
  [params.Social_media.Instagram]
    Url = "https://example.com"
  [params.Social_media.Twitter]
    Url = "https://example.com"

  [params.presentation]
    title = "À propos"
    text = [
      "Age : 24 Ans",
      "Langues : Francais & Anglais courant",
      "Mobilité : Permis internationnal & Passeport",
      "Style Musical : GÉNÉRALISTE",
      "Influences : Bass House, Brazilian Bass, Deep House, Hip-Hop, Trap, Actu, EDM, Psy Trance, Urban, retro, 80's/90's/00's.",
    ]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Événements"
    url = "/events/"
    weight = 2
  [[menu.main]]
    name = "Équipements"
    url = "/equipement"
    weight = 3
  [[menu.main]]
    name = "Galerie"
    url = "/gallery/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5
