baseURL = 'https://example.org/'
languageCode = 'fr'
title = 'DJ RESCH'
theme = 'ananke'
enableEmoji = true
# enableRobotsTXT = true
# canonifyURLs = true
# paginate = 9
# enableInlineShortcodes = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  site_logo = "favicon/favicon-32x32.png"
  description = "Bienvenue sur le site officiel de DJ RESCH"
  author = "DJ RESCH"
  email = "djreschbooking@gmail.com"
  customCSS = ["css/custom.css"]
  favicon = "favicon/favicon-32x32.png"
  [params.Social_media.Facebook]
    Url = "https://example.com"
  [params.Social_media.Instagram]
    Url = "https://example.com"
  [params.Social_media.Twitter]
    Url = "https://example.com"

  [params.presentation]
    title = "À propos"
    text = [
      "Age : 24 Ans",
      "Langues : Francais & Anglais courant",
      "Mobilité : Permis internationnal & Passeport",
      "Style Musical : GÉNÉRALISTE",
      "Influences : Bass House, Brazilian Bass, Deep House, Hip-Hop, Trap, Actu, EDM, Psy Trance, Urban, retro, 80's/90's/00's.",
    ]

  [params.weddingsService]
    link = "https://www.mariages.net/musique-mariage/resch--e316860"
  [params.weddingsServiceRate]
    link = "https://www.mariages.net/musique-mariage/resch--e316860/avis"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  # [[menu.main]]
  #   identifier = "dj"
  #   name = "DJ / Showcases"
  #   url = "/dj/dates"
  #   weight = 2
  #   [[menu.main]]
  #     parent = "dj"
  #     name = "Dates"
  #     url = "/dj/dates"
  #     weight = 1
  #   [[menu.main]]
  #     parent = "dj"
  #     name = "Photos"
  #     url = "/dj/photos"
  #     weight = 2
  #   [[menu.main]]
  #     parent = "dj"
  #     name = "Cours de DJing"
  #     url = "/dj/djing"
  #     weight = 3
  [[menu.main]]
    name = "Musiques"
    url = "/musics"
    weight = 3
  [[menu.main]]
    identifier = "wedding"
    name = "Mariages"
    url = "/weddings/services"
    weight = 4
  #   [[menu.main]]
  #     parent = "wedding"
  #     name = "Services"
  #     url = "/weddings/services"
  #     weight = 1
  #   [[menu.main]]
  #     identifier = "wedding-photo"
  #     parent = "wedding"
  #     name = "Photos"
  #     url = "/weddings/photos"
  #     weight = 2
  # [[menu.main]]
  #   identifier = "about"
  #   name = "À propos"
  #   weight = 5
  #   [[menu.main]]
  #     parent = "about"
  #     name = "Bio"
  #     url = "/about/bio"
  #     weight = 1
  #   [[menu.main]]
  #     parent = "about"
  #     name = "Book TV"
  #     url = "/about/book-tv"
  #     weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6
