name: Pull Rates

on:
  schedule:
    - cron: "0 3 * * *"  # Runs daily at 03:00 UTC
  workflow_dispatch:     # Allow manual run from GitHub UI

jobs:
  pull-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium beautifulsoup4

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb
        sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb
        export CHROME_BIN=google-chrome-stable
        export PATH=$PATH:/usr/bin/google-chrome-stable

    - name: Run pull-rates.py
      run: python pull-rates.py

    - name: Commit new rates if any
      if: success() && hashFiles('have_new_rate.txt') != ''
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add content/footer/rates
        git commit -m "Update rates: $(date -I)"
        git push
